### PR TITLE
Integrate H5Z-SZ3 into master

### PR DESCRIPTION
**Pull request by 123epsilon**

### CODE REVIEW

**Comment by ayzk** [comment]
@disheng222 Personally I prefer to put this hdf5-sz code in a separate branch instead of merging it to the master branch, since not everyone needs hdf5 support. Another way is to put hdf5-sz in master and add a switch to control whether it will be compiled or not (the default value should be false).

**Comment by disheng222** [comment]
I suggest to add a switch to control whether it is compiled. H5Z-SZ3 filter could be disabled by default. 
I believe many people are using HDF5 so H5Z filter is a very important module for usability. :P

**Comment by ayzk** [comment]
> I suggest to add a switch to control whether it is compiled. H5Z-SZ3 filter could be disabled by default. I believe many people are using HDF5 so H5Z filter is a very important module for usability. :P

Sure. @123epsilon Please add the switch in cmake. Thanks.

**Comment by 123epsilon** [comment]
Sure, the branch is updated to reflect those changes.

**Comment by ayzk** [comment]
> Sure, the branch is updated to reflect those changes.
Please also update the makefile and the .h file

**Comment by 123epsilon** [comment]
Currently the filter only supports CMake, I have removed the Makefile in master as currently it is not usable. What needs to be changed in the header?

**Comment by ayzk** [comment]
> Currently the filter only supports CMake, I have removed the Makefile in master as currently it is not usable. What needs to be changed in the header?

The makefile is still there. Could you delete the file? For the header, please rename it as *.hpp instead *.h

**Comment by 123epsilon** [comment]
Ok, the Makefile is deleted now and the header is renamed.

**Comment by ayzk** [comment]
> Ok, the Makefile is deleted now and the header is renamed.

This branch has been merged to master. However, I notice there are some warnings during the build process. Could you remove them? By the way, H5Z-SZ3 is in the 'tools' folder now.

**Comment by ayzk** [comment]
> Ok, I've dealt with the two warnings in H5Z-SZ3.cpp/hpp with some small changes. There is also a warning about narrowing conversions from int to short unsigned int in the PolyRegressionPredictor.hpp. Do you want me to suppress these or leave them as is?

Thanks. You can leave the warning about regression.

**Comment by 123epsilon** [comment]
Ok, the fixes are present in the master branch of my fork now.

**Pull request merged**
